### ISSUE TITLE
Icon Labels

### ISSUE THREAD

**Issue by rctfan929** [ajaidan/Mavalry#2]
Icon labels are always not displayed even when ‘hide icon labels’ is off.

iPhone 6s iOS 13.5 unc0ver 5.2.0

**Comment by ajaidan** [comment]
Can you explain this problem more in-depth?  I’ve had several people report this, yet not a single one of our beta testers experienced this issue.

Best Regards,

ajaidan0

**Comment by ajaidan** [comment]
Closing as not caused by our tweak

**Comment by rctfan929** [comment]
Settings
![1CFB57D4-7737-4B03-A3A9-9A02F2A22A74](https://user-images.githubusercontent.com/46878212/85495293-3a91fa80-b5a8-11ea-882e-3ad664665b3b.png)
Appearance
![2F413267-4AED-4F7F-8599-04F3F692466A](https://user-images.githubusercontent.com/46878212/85495343-55646f00-b5a8-11ea-8f0c-08b3d66ba9ff.png)

**Comment by ajaidan** [comment]
I just don't understand how that could be my tweak...

**Comment by ajaidan** [comment]
UPDATE: I BELIEVE I FOUND THE ISSUE, SHOULD BE RESOLVED NEXT UPDATE

**Comment by rctfan929** [comment]
Just took a lot of resprings to make it work.
